# Generated by Django 6.0.7 on 2026-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='inventory_received',
            field=models.BooleanField(default=False),
        ),
    ]
