# Generated by Django 6.0.7 on 2026-08-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_branch_userprofile_company'),
        ('logistics', '0002_shipment_inventory_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='accounts.branch'),
        ),
    ]
