# Generated by Django 6.0.7 on 2026-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('administration', 'Administration'), ('procurement', 'Procurement'), ('inventory', 'Inventory'), ('warehouse', 'Warehouse'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('supply_chain', 'Supply Chain')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('supply_chain_manager', 'Supply Chain Manager'), ('manager', 'Department Manager'), ('officer', 'Officer'), ('viewer', 'Viewer')], default='viewer', max_length=30),
        ),
    ]
