# Generated by Django 6.0.7 on 2026-08-05 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('supply_chain_manager', 'Supply Chain Manager'), ('procurement_officer', 'Procurement Officer'), ('warehouse_manager', 'Warehouse Manager'), ('inventory_officer', 'Inventory Officer'), ('logistics_officer', 'Logistics Officer'), ('finance_officer', 'Finance Officer'), ('viewer', 'Viewer')], default='viewer', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
