# Generated by Django 6.0.7 on 2026-09-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_branch_options_alter_company_options_and_more'),
        ('procurement', '0003_purchaseorderitem_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchase_orders', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_purchase_orders_items', to='accounts.branch'),
        ),
    ]
