# Generated by Django 6.0.7 on 2026-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('shipment_delay', 'Shipment Delay'), ('overdue_po', 'Overdue Purchase Order'), ('procurement_handoff', 'Procurement Handoff')], max_length=30),
        ),
    ]
