# Generated by Django 6.0.7 on 2026-08-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('ltr', 'Litres'), ('box', 'Boxes'), ('carton', 'Cartons'), ('bag', 'Bags')], default='pcs', max_length=20),
        ),
    ]
